// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP9p0HkQVKQy6ZnwbGNT_7tj5uxQ-msdk',
    appId: '1:265976116111:web:fe9296ee4f647c9788d1fa',
    messagingSenderId: '265976116111',
    projectId: 'facebook-basic-layout',
    authDomain: 'facebook-basic-layout.firebaseapp.com',
    storageBucket: 'facebook-basic-layout.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv6pDblbI58-OK0C_jDkLDyhSoZTHkJ6g',
    appId: '1:265976116111:android:dcdb38cb9d91d59f88d1fa',
    messagingSenderId: '265976116111',
    projectId: 'facebook-basic-layout',
    storageBucket: 'facebook-basic-layout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpTRPUkOMrXG6jrjO4JsWiEklZ0BaiKr4',
    appId: '1:265976116111:ios:ddb0286e2561346c88d1fa',
    messagingSenderId: '265976116111',
    projectId: 'facebook-basic-layout',
    storageBucket: 'facebook-basic-layout.appspot.com',
    iosClientId: '265976116111-lviknn47m9ljbl367d7tfuc2unf8q41k.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicLayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpTRPUkOMrXG6jrjO4JsWiEklZ0BaiKr4',
    appId: '1:265976116111:ios:ddb0286e2561346c88d1fa',
    messagingSenderId: '265976116111',
    projectId: 'facebook-basic-layout',
    storageBucket: 'facebook-basic-layout.appspot.com',
    iosClientId: '265976116111-lviknn47m9ljbl367d7tfuc2unf8q41k.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicLayout',
  );
}
